import "./globals.css";
import { NextAuthProvider } from "./providers";

export const metadata = {
  title: {
    template: "%s | 서울 로봇고등학교 커뮤니티 Speedat",
    default: "서울 로봇고등학교 커뮤니티 Speedat",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  );
}
